import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Fixed font import
import "./globals.css";
import Link from "next/link";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}> {/* Ensure font is applied */}
      <body>
        <nav className="bg-gray-900 text-white p-4 flex justify-center gap-4">
          <Link href="/home" className="hover:underline">Home</Link>
          <Link href="/about" className="hover:underline">About</Link>
          <Link href="/blog" className="hover:underline">Blog</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
